server:
  port: 9096

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/akshayjadhav2395/Microservices-project-Config-Server
          clone-on-start: true